services:
  booking_users_db:
    image: postgres:17-alpine
    container_name: booking_users_db
    restart: always
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - user-network

  booking_user-service:
    container_name: booking_users_service
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    ports: 
      - 9001:9001
    depends_on:
      - booking_users_db
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - user-network
    env_file:
      - ./user-service/.env-dev

volumes:
  pgdata:

networks:
  user-network:
