events {}

http {
  server {
    listen 80;
    
    location /api/v1/user/ {
      proxy_pass http://user_service:9001/;
    }

    location /api/v1/property/ {
      proxy_pass http://property_service:9002/;
    }

    location / {
      return 404;
    }
  }
}