services:
  db:
    image: postgres:17
    container_name: user_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/libg/postgresql/data
    networks:
      - user-network
  user-service:
    container_name: user_service
    build: .
    ports: 5000:5000
    depends_on:
      - db
    networks:
      - user-network

volumes:
  pgdata:
networks:
  user-network: