services:
  db:
    image: postgres:17
    container_name: user_db
    restart: always
    ports:
      - 9432:5432
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/libg/postgresql/data
    networks:
      - user-network
  user-service:
    container_name: user_service
    build: .
    ports: 
     - 9000:9000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - user-network

volumes:
  pgdata:
networks:
  user-network: