services:
  booking_users_db:
    image: postgres:17-alpine
    container_name: booking_users_db
    restart: always
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - user-network

  booking_user-service:
    container_name: booking_users_service
    build: .
    ports: 
      - 9000:9000
    depends_on:
      - booking_users_db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - user-network
    env_file:
      - ./.env

volumes:
  pgdata:

networks:
  user-network:
