CREATE USER booking WITH
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  INHERIT
  NOREPLICATION
  CONNECTION LIMIT -1
  PASSWORD 'yzPV225HeSWv';

CREATE DATABASE "booking-users"
    WITH 
    OWNER = booking
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;